### ISSUE TITLE
Class 'Redis' Not Found

### ISSUE THREAD

**Issue by Jamandro** [cloudex99/AnimeCMS#1]
Fatal error: Uncaught Error: Class 'Redis' not found in C:\wamp64\www\Anime\app\library\Cache.php on line 27 
Anything About this ?

**Comment by cloudex99** [comment]
You can comment out the contents of the redis() function in Cache.php or install a redis-server and the phpredis extension for php.

**Comment by Jamandro** [comment]
I have Figured this but the when i hit the localhost/Anime/public it says the localhost has redirected you many times 
Do I also have to change these following lines of code
const API_URL = 'https://animeapi.com';
const API_KEY = '*****************************';
Because as far as i am concerned the https://animeapi.com link does not work

**Comment by Jamandro** [comment]
$auth_mw = function ($request, $response, $next) {

    User::init();
    
    if (!User::isLoggedIn())
    {
        // redirect the user to the login page and do not proceed.
        $response = $response->withRedirect(SITE_URL.'/login');
    }
    elseif(!User::hasAccess()){
        $_SESSION['_msg'] = 'Not allowed';
        $response = $response->withRedirect('/');
    }
    else {
        // Proceed as normal...
        $response = $next($request, $response);
    }

    return $response;
};
The Code Breaks Before These Lines Of Code

**Comment by cloudex99** [comment]
You do not change that!!! It is the heart of the system.

Also the code has not been tested on a Windows environment at all. I would
recommend using a Linux based environment to avoid any issues. You can
setup a local Linux development environment using Vagrant on Windows.

**Comment by Jamandro** [comment]
I have tried In Linux base server But still redirected Many Times.Have you any idea what this might be? 
I have given SITE_URL : localhost/Foldername/public But it is saying redirected many times ???
