### ISSUE TITLE
The Localhost redirected you many time

### ISSUE THREAD

**Issue by Jamandro** [cloudex99/AnimeCMS#2]
The files are in anime folder and the SITE_URL is given localhost/anime and when i hit it in the browser it says Localhost redirected you so many time and url becomes **localhost/anime/anime**.The Server is LAMP on ubuntu 18

**Comment by cloudex99** [comment]
Your rewrite rules are probably not correct.

Here is an example apache virtual host config:
`<VirtualHost *:80>
	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/AnimeCMS/public
    
	<Directory "/var/www/AnimeCMS/public">
        Options Indexes FollowSymLinks
		AllowOverride None
		Require all granted
        ReWriteEngine On
        RewriteBase /
    	RewriteCond %{REQUEST_FILENAME} !-f
		RewriteCond %{REQUEST_FILENAME} !-d
		RewriteRule ^ index.php [QSA,L]
    </Directory>
    
    <FilesMatch \.php$>
    	SetHandler "proxy:unix:/var/run/php/php7.2-fpm.sock|fcgi://localhost/"
	</FilesMatch>

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>`

The SITE_URL is set to localhost for this specific config.
