### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by AsmodeusX00** [cloudex99/AnimeCMS#3]
Fatal error: Uncaught Error: Call to undefined function Cloud\apcu_exists() in /homepages/36/d783109242/htdocs/app/library/Cache.php:80 Stack trace: #0 /homepages/36/d783109242/htdocs/app/library/Config.php(18): Cloud\Cache::exists('cms_settings') #1 /homepages/36/d783109242/htdocs/public/index.php(15): Config::init() #2 {main} thrown in /homepages/36/d783109242/htdocs/app/library/Cache.php on line 80

I feel like I'm doing something terribly wrong haha

**Comment by cloudex99** [comment]
You do not have the apcu php extension installed.
