### ISSUE TITLE
Vendor Folder missing - solved, thanks.

### ISSUE THREAD

**Issue by intenso09** [cloudex99/AnimeCMS#4]
autoload.php failed to open stream. Autoload should be in the vendor folder but it's missing.

**Comment by rwadud** [comment]
You can populate the vendor folder by running this command in the same directory as composer.json: `composer install`

**Comment by cloudex99** [comment]
``You can populate the vendor folder by running this command in the same directory as composer.json: composer install

You would obviously need composer installed.
