### ISSUE TITLE
Unexpected data in output buffer. Maybe you have characters before an opening <?php tag?

### ISSUE THREAD

**Issue by PlutusZero** [cloudex99/AnimeCMS#6]
Hey, don't know if this repository is still active or not but I'm having some problems. I have php7.0 installed, I installed composer and the dependencies, I've changed the config.php file, and installed apcu. However, I keep getting errors thrown at me. 
<img width="860" alt="issue1" src="https://user-images.githubusercontent.com/60773042/74014149-11a3fc80-495c-11ea-8776-7b704dd89501.png">
<img width="998" alt="issue2" src="https://user-images.githubusercontent.com/60773042/74014152-12d52980-495c-11ea-8bfd-4cd71850c2e1.png">
<img width="956" alt="issue3" src="https://user-images.githubusercontent.com/60773042/74014153-136dc000-495c-11ea-9635-5367b5d9f0a0.png">
<img width="990" alt="issue4" src="https://user-images.githubusercontent.com/60773042/74014155-14065680-495c-11ea-96d2-6fb1d8f704f3.png">

Also using nginx on Debian 9

**Comment by rwadud** [comment]
Try installing apcu_bc.

**Comment by PlutusZero** [comment]
> Try installing apcu_bc.

Will try that when I get home from work. Thanks
